# Generated by Django 3.1.5 on 2022-11-06 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
