# Generated by Django 3.1.5 on 2022-11-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20221129_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='This will be the first comment', max_length=255),
            preserve_default=False,
        ),
    ]
