# Generated by Django 3.1.5 on 2022-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(default='', upload_to='pcis/category/banner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(default='', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail_image',
            field=models.ImageField(default='', upload_to='pics/category/thumbnail'),
            preserve_default=False,
        ),
    ]
