# Generated by Django 3.1.5 on 2022-11-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20221129_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('picture', models.ImageField(upload_to='pics/testimonials/')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='pcis/category/banner'),
        ),
    ]
