# Generated by Django 3.1.5 on 2022-12-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_category_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
